# Generated by Django 3.2 on 2021-07-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0002_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='job',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
