# Generated by Django 3.2 on 2021-07-30 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        ('patientdata', '0003_auto_20210729_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('complain', models.TextField(blank=True, null=True)),
                ('sign', models.TextField(blank=True, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=150, null=True)),
                ('intervention', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.patients')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.visits')),
            ],
        ),
    ]
