# Generated by Django 3.2 on 2021-07-27 21:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasthist', models.CharField(blank=True, max_length=150, null=True)),
                ('histdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('remarknote', models.CharField(blank=True, max_length=1000, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.patients')),
            ],
        ),
    ]
